version: '3.8'

services:
  # Serviço 1: Aplicação PHP/Apache
  app:
    build: . 
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/

  # Serviço 2: Banco de Dados MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: # IMPLEMENTE UMA SENHA SEGURA AQUI PARA SEU BANCO
      MYSQL_DATABASE: autorizador_db
    ports:
      - "3308:3306" # NOVO MAPEMANETO: 3308 no Host, 3306 no Container